pipeline:
  name: conduit-flask
  identifier: conduitflask
  projectIdentifier: k3d
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1723535805475
        repoName: GHruXebia/conduit-flask
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k3dmac
              namespace: harness-ci
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: python:3.11-slim
                    shell: Sh
                    command: |
                      apt-get update && apt-get install -y python3-dev cargo && pip install poetry && poetry install && poetry run pytest
